# Generated by Django 3.2.9 on 2022-01-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(default='', max_length=100),
        ),
    ]
